### ISSUE TITLE
Remove newline character after table name

### ISSUE THREAD

**Issue by xg5-simon** [AttackIQ/pySigma-backend-kusto#20]
Hi Team,

First, awesome work on this sigma backend! 

The `finalize_query_default` function in the microsoft365defender.py backend has a hardcoded \n . This is great for an analysts readability when printing the rule to the terminal but has the potential to break when creating rules to be consumed by an API.

FYSA, I'm using the following post processing pipeline to convert sigma rules to KQL wrapped in JSON for use with the MDE API and the rule is rendered as:

```JSON
  {
    "queryDescription": "Uncommon Child Process Of AddinUtil.EXE",
    "query": "DeviceProcessEvents 
| where InitiatingProcessFolderPath endswith \"\\addinutil.exe\""
  }
```

#### mdepipeline.yml
```YAML
postprocessing:
- type: template
  template: |+
    {
      "queryDescription": "{{ rule.title }}",
      "query": "{{ query }} | order by Timestamp asc"
    }
finalizers:
- type: concat
  separator: |
    ,
  prefix: |
    [
  suffix: |
    ]
```

My recommendation is to remove the hard coded newline to support rule conversion to be consumed by APIs and users can use the Format Document or Format Selection options within MDE or Sentinel.
